PROP_TABLE_COUNT = 116

# data section offsets
PROP_TABLE_OFFSET = 0x159DA0
MAP_TABLE_OFFSET = 0xE7F0

# raw_addresses
DATA_SECTION_RAW_ADDRESS = 0x001C1000

# chunk magic numbers
TEXTURE_MAGIC = 0x0241
TEXTURE_TYPE_SPEC = 0x0408
ESCAPE = b"\xff\x00\x00\x00"

# io
MEDIA_DIRECTORY_NAME = "media"
SECTION_ADDRESS_FILE_NAME = "sectionaddress.csv"
XBE_FILE_NAME = "default.xbe"
